on:
  workflow_dispatch:

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            system = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: |
          nix -L build --update-input nixpkgs 'nixpkgs/nixos-unstable' --no-write-lock-file 'github:patryk4815/ctftools?dir=lima-vm#packages.aarch64-linux.box'
          ls result
