on:
  release:
    types: [published]
  push:
  workflow_dispatch:

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Install QEMU
        run: sudo apt-get install -y qemu-user-static
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            system = aarch64-linux
            system-features = nixos-test benchmark big-parallel kvm
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: |
          NIXPKGS_HASH=$(nix flake metadata nixpkgs --json | jq -r '.locked.rev[0:7]')
          nix -L build '.#packages.aarch64-linux.box'
          cp result/*.img "nixos-${NIXPKGS_HASH}.img"
      - name: Upload image
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: |
            *.img
          upload-signing-artifacts: true
          release-signing-artifacts: true
