on:
  release:
    types: [published]
  push:
  workflow_dispatch:

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v3
      - name: Install QEMU
        run: sudo apt-get install -y qemu-user-static
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            system = aarch64-linux
            system-features = nixos-test benchmark big-parallel kvm
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: |
          NIXPKGS_HASH=$(nix flake metadata nixpkgs --json | jq -r '.locked.rev[0:7]')
          nix -L build '.#packages.aarch64-linux.image'
      - name: Sign image
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            result/*.raw.zst
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          path: |
            result/*.raw.zst
